######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 7 15:37:18 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
#QT += multimedia
CONFIG += debug
LIBS += -lportaudio

# Input
HEADERS += main_window.h sound_thread_portaudio.h
SOURCES += main.cpp main_window.cpp sound_thread_portaudio.cpp
